// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDATb0RUGG3-OqvXPfcPSdKoUBu_SNGExY',
    appId: '1:1069564701923:web:5009917c94ba02a82629d6',
    messagingSenderId: '1069564701923',
    projectId: 'hao-lin-ju',
    authDomain: 'hao-lin-ju.firebaseapp.com',
    storageBucket: 'hao-lin-ju.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdYzDhdA4JmaS5LHLPLaa1RsAwbCApunU',
    appId: '1:1069564701923:android:0ebb72189ea1ff8c2629d6',
    messagingSenderId: '1069564701923',
    projectId: 'hao-lin-ju',
    storageBucket: 'hao-lin-ju.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcdlmqMAwWt5bqjDLb_e4gCZsH5VyU1OI',
    appId: '1:1069564701923:ios:cb3246f61122e25e2629d6',
    messagingSenderId: '1069564701923',
    projectId: 'hao-lin-ju',
    storageBucket: 'hao-lin-ju.appspot.com',
    iosClientId: '1069564701923-t56ggc875ae4d6lsp41vvkddf0fk9ber.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcdlmqMAwWt5bqjDLb_e4gCZsH5VyU1OI',
    appId: '1:1069564701923:ios:b6ce5890d46021e62629d6',
    messagingSenderId: '1069564701923',
    projectId: 'hao-lin-ju',
    storageBucket: 'hao-lin-ju.appspot.com',
    iosClientId: '1069564701923-jsfah4a9dcadbrd4bvnru4itg7b4linj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth.RunnerTests',
  );
}
